app/build.gradle, app/src/main/java/bluepie/ad_silence/AppNotification.kt
**This pr should extend support till android 5, the current support is from android 9 and above.**
=> extend support for android 5 and above.

README.md, app/build.gradle, app/src/main/AndroidManifest.xml, app/src/main/java/bluepie/ad_silence/AdSilenceActivity.kt, app/src/main/java/bluepie/ad_silence/AppNotification.kt, app/src/main/java/bluepie/ad_silence/NotificationParser.kt, app/src/main/java/bluepie/ad_silence/Preference.kt, app/src/main/java/bluepie/ad_silence/SupportedApps.kt, app/src/main/java/bluepie/ad_silence/Utils.kt, app/src/main/res/layout/app_selection.xml, app/src/main/res/values/strings.xml
**This pr should extend support for Spotify-lite**
closes #12
=> Support spotify lite

app/build.gradle, app/src/main/AndroidManifest.xml, app/src/main/java/bluepie/ad_silence/AdSilenceActivity.kt, app/src/main/java/bluepie/ad_silence/NotificationParser.kt, app/src/main/java/bluepie/ad_silence/Preference.kt, app/src/main/java/bluepie/ad_silence/SupportedApps.kt, app/src/main/java/bluepie/ad_silence/Utils.kt, app/src/main/res/layout/app_selection.xml, app/src/main/res/values/strings.xml
**This pr extends support for Pandora**
play store link: https://play.google.com/store/apps/details?id=com.pandora.android
=> Add support for pandora

app/src/main/res/values-it-rIT/strings.xml, app/src/main/res/values/strings.xml
I added the Italian translation
=> Added Italian translation

app/build.gradle, app/src/main/AndroidManifest.xml, build.gradle, gradle/wrapper/gradle-wrapper.properties
https://trello.com/c/wfSkmBQU/56-update-gradle
=> Update gradle to 7.2.1

app/build.gradle
update dependencies and check if app works without issues
```diff
-    implementation 'androidx.core:core-ktx:1.3.2'
-    testImplementation 'junit:junit:4.+'
-    androidTestImplementation 'androidx.test.ext:junit:1.1.2'
-    androidTestImplementation 'androidx.test.espresso:espresso-core:3.3.0'
+    implementation 'androidx.core:core-ktx:1.8.0'
+    testImplementation 'junit:junit:4.13.2'
+    androidTestImplementation 'androidx.test.ext:junit:1.1.3'
+    androidTestImplementation 'androidx.test.espresso:espresso-core:3.4.0'
```
=> update ktx & dependencies

Changelog/README.md, README.md, app/build.gradle, fastlane/metadata/android/en-US/changelogs/40.txt
**This pr should capture all the changes from v0.5.4 - v0.5.5**
=> Release 0.5.5

.github/workflows/android.yml
+ add build pipeline for automated builds
=> build pipeline

.github/workflows/android.yml, app/build.gradle
This pr adds pipeline config to automate debug builds on every pull request to `development` and `master` branches.
=> Pipeline changes

Changelog/README.md, README.md, app/build.gradle, fastlane/metadata/android/en-US/changelogs/42.txt
- Changes for next release
- change log
- fastlane
- app versions
=> Release v0.6.0

app/src/main/java/bluepie/ad_silence/About.kt, app/src/main/java/bluepie/ad_silence/AdSilenceActivity.kt
**Changes:**
+ Add version information next to title in about
+ refactor about dialog to separate file
=> Adds version name & version number in about view.

app/build.gradle, app/src/main/java/bluepie/ad_silence/AdSilenceActivity.kt, app/src/main/java/bluepie/ad_silence/Hibernation.kt, app/src/main/java/bluepie/ad_silence/Preference.kt, app/src/main/res/layout/permission_granting.xml, app/src/main/res/values-it-rIT/strings.xml, app/src/main/res/values/strings.xml, build.gradle
**This PR handles hibernation for the app**
[https://developer.android.com/topic/performance/app-hibernation](https://developer.android.com/topic/performance/app-hibernation)
=> Hibernation

app/src/main/java/bluepie/ad_silence/NotificationParser.kt
Reported from poco f5, miui os. Accuradio causes crash.
=> Fix Accuradio not working on high dpi devices

.gitignore, app/build.gradle, app/src/main/java/bluepie/ad_silence/AdSilenceActivity.kt, app/src/main/java/bluepie/ad_silence/NotificationParser.kt, app/src/main/java/bluepie/ad_silence/Preference.kt, app/src/main/java/bluepie/ad_silence/SupportedApps.kt, app/src/main/java/bluepie/ad_silence/Utils.kt, app/src/main/res/layout/app_selection.xml, app/src/main/res/values-it-rIT/strings.xml, app/src/main/res/values/strings.xml
This pr adds support for sound cloud. 
Closes #104 #94
=> Feat: add soundcloud

app/src/main/AndroidManifest.xml, app/src/main/res/values/strings.xml
=> fix: add missing commits

app/src/main/java/bluepie/ad_silence/AdSilenceActivity.kt, app/src/main/res/layout/permission_granting.xml, app/src/main/res/values-it-rIT/strings.xml, app/src/main/res/values/strings.xml
Add information on the [new android restricted settings](https://support.google.com/android/answer/12623953?sjid=3702608675861705680-AP#allowrestrictedsettings) in mainview and link the wiki here 
https://github.com/aghontpi/ad-silence/wiki/Restricted-Setting-or-Unable-to-grant-notification-permission
closes #103
=> Add info on restricted settings

Changelog/README.md, README.md, app/build.gradle, fastlane/metadata/android/en-US/changelogs/49.txt, fastlane/metadata/android/en-US/full_description.txt
**Prep work for release 0.6.1**
=> Release/release work 0.6.1

build.gradle, gradle.properties
This pr updates the android build grade to latest, i.e 8.8.2
=> chore: update build tools to 8.8.2

app/build.gradle, app/src/main/AndroidManifest.xml
This PR updates the android version from android 13 to android 14.
=> feature: update to android 14, sdk 34

app/build.gradle, app/src/main/AndroidManifest.xml
This pull request updates the project to target Android 15 by making the following changes:
**Build Configurations:**
- Updated compileSdk from 33 to 35.
- Updated targetSdk from 33 to 35 (aligned with Android 15 requirements).
- Adjusted versioning: switched from versionName "0.6.1-prod" to "0.6.2-dev".
=> feature: update to android 15, sdk 35

app/src/main/java/bluepie/ad_silence/AdSilenceActivity.kt, app/src/main/java/bluepie/ad_silence/Permission.kt
Some devices does not have UI for granting permission, like android TV.
=> Fix crash on android_tv, other devices where acitvity is not there. 
